name: "publish 🚀"
on:
  release:
    types: [published]
jobs:
  release:
    name: publish 🚀
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: setup node 🟢
      uses: actions/setup-node@v2
      with: 
        node-version: 12
        registery-url: https://registry.npmjs.org
    - name: publish 🚀
      run: npm publish --access public 
      env: 
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} 